# Ubuntu 22.04 non-nvida (jazzy)
FROM osrf/ros:jazzy-desktop-full

# Author Information
LABEL author="Bruce Chan Jian Le <jianle001@e.ntu.edu.sg>"
LABEL maintainer="Bruce Chan Jian Le <jianle001@e.ntu.edu.sg>"
LABEL website="https://github.com/BruceChanJianLe/docker-nvidia-ubuntu-ros"
LABEL license="MIT"

# Set colorful prompt
ENV TERM xterm-256color

# Set LANG in order to display emoji
ENV LANG en_US.UTF-8
# Require for ansible
ENV LC_ALL C.UTF-8

RUN apt-get update -qq \
    && DEBIAN_FRONTEND=noninteractive apt-get install -y -qq \
    # Build Tools
    build-essential cmake git wget curl lsb-release software-properties-common sudo \
    # Debugging & Analysis
    gdb cppcheck htop tmux vim bash-completion bc python3-dbg \
    # ROS/Hardware Dependencies
    libbluetooth-dev libcwiid-dev libgoogle-glog-dev libspnav-dev libusb-dev libyaml-cpp-dev \
    # Python Environment
    python3-numpy python3-setuptools python3-pip python3-venv python3-empy python3-pynvim \
    # Networking
    net-tools iputils-ping ansible \
    # GUI/XCB Fixes (Fixes the RViz plugin error)
    libxcb-xinerama0 libxcb-icccm4 libxcb-image0 libxcb-keysyms1 libxcb-render-util0 libxcb-xkb1 libxkbcommon-x11-0 libqt5gui5 \

    # Neovim Search Tools (Essential for Telescope/Plugins)
    ripgrep fd-find xclip \
    && apt-get clean -qq \
    && rm -rf /var/lib/apt/lists/*

# Add a user with the same user_id as the user outside of the container
# Note that this requires a docker build argument `user_id`
ARG user_id
ENV USERNAME isera2
RUN if id -u ${user_id} >/dev/null 2>&1; then userdel -r $(id -un ${user_id}); fi \
    && useradd -U --uid ${user_id} -ms /bin/bash $USERNAME \
    && echo "$USERNAME:$USERNAME" | chpasswd \
    && adduser $USERNAME sudo \
    && echo "$USERNAME ALL=NOPASSWD: ALL" >> /etc/sudoers.d/$USERNAME

# Commands below are run as developer user
USER $USERNAME

# Let the container starts in the developer's home folder
WORKDIR /home/$USERNAME

# Make a mounting directory
RUN mkdir -p /home/$USERNAME/docker_mount

# Export noninterative tzdata
RUN export DEBIAN_FRONTEND=noninteractive \
 && sudo apt-get update && sudo apt-get install -y tzdata

# Setup dotfiles
RUN ansible-pull -U https://github.com/yuda226/ansible.git --skip-tags additional
# RUN ansible-pull -U https://github.com/brucechanjianle/ansible -i localhost, -e "ansible_connection=local" local.yml --skip-tags additional

# Declare inside container
ENV IN_DOCKER 1

# config & cleanup
RUN sudo apt-get clean -y -qq \
    && sudo apt-get autoremove -y -qq \
    && sudo rm -rf /var/lib/apt/lists/* /tmp/*

